### PR TITLE
Update to Kubernetes 1.25

### PR DESCRIPTION
**Pull request by nvollmar**

### CODE REVIEW

**Comment by pjfanning** [comment]
* seems ok because this is really just affecting tests
* one issue is that we are hitting rate limits - https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting
* would you be able to change the github workflow to use the pass on the GITHUB_TOKEN ?

**Comment by nvollmar** [comment]
Yep, thought might be time to upgrade as 1.20 isn't supported anymore and we should test against something kind of current.
Downgraded to 1.22 which seems to work fine for now.

**Comment by nvollmar** [comment]
Great, I'll just rebase and retest once you merged.

**Comment by pjfanning** [comment]
#27 is merged now - thanks

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
