### PR TITLE
test with latest scala releases

### PR DESCRIPTION
**Pull request by pjfanning**
* also sbt 1.9.7
* sbt plugin updates

### CODE REVIEW

**Review by nvollmar — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
@pjfanning I think this PR will break the github actions, you need to modify the sbt command to accept just major + minor, no?

**Comment by pjfanning** [comment]
@mdedetrich I merged this before your comment. The unit tests passed in the PR CI run. The unit test yml had a similar change to the nightly yml and the unit tests ran ok (1 intermittent test failed in Scala 3 run).

I've started a nightly test run just in case and if that fails, I'll submit a revert or fix. 

There is an open issue for the nightly tests - #132

**Comment by pjfanning** [comment]
@mdedetrich nightly run (forced to run by me just now) was ok. It had the expected test failures but scala version wasn't an issue.

expected test failures described in https://github.com/apache/incubator-pekko-management/issues/132

**Pull request merged**
