### PR TITLE
add MIT license for some test scripts

### PR DESCRIPTION
**Pull request by pjfanning**
see https://lists.apache.org/thread/l847ccsc0mr4yp33nlxtmnf4mrzqx5hv

### CODE REVIEW

**Comment by pjfanning** [comment]
this is required before we attempt an RC2

**Comment by pjfanning** [comment]
@mdedetrich Would you have time to review this? This change allows us to do an RC2.

**Review by mdedetrich — APPROVED** [review]
lgtm

**Review by He-Pin — APPROVED** [review]
Lgtm

**Pull request merged**
