### PR TITLE
[Draft] Publish

### PR DESCRIPTION
**Pull request by nvollmar**

### CODE REVIEW

**Comment by nvollmar** [comment]
@mdedetrich I'm one step further:
> [error] Unable to find credentials for [Sonatype Nexus Repository Manager @ repository.apache.org].

**Comment by mdedetrich** [comment]
@nvollmar Can you temporarily set `apacheSonatypeCredentialsLogLevel` to `Level.Warn` as documented at https://github.com/mdedetrich/sbt-apache-sonatype#notable-sbt-plugin-keys to verify that credentials are missing?

**Comment by mdedetrich** [comment]
Also need to change `sbt -jvm-opts .jvmopts-ghactions +publish` to `sbt +publish`

**Comment by mdedetrich** [comment]
Okay we got something

```
Both NEXUS_USER and NEXUS_PW environment variables for Apache Maven Nexus repo are empty strings
```

**Comment by mdedetrich** [comment]
Ticket created https://issues.apache.org/jira/browse/INFRA-24284

**Comment by nvollmar** [comment]
Thanks

**Comment by pjfanning** [comment]
> Okay we got something
> 
> ```
> Both NEXUS_USER and NEXUS_PW environment variables for Apache Maven Nexus repo are empty strings
> ```
> 
> Have to make an INFRA ticket

We've hit this a few times. Could you add a list of all this repo and a few others that we have made progress on - where we will soon also be publishing?

* incubator-pekko-connectors
* incubator-pekko-connectors-kafka
* incubator-pekko-grpc
* incubator-pekko-management
* incubator-pekko-persistence-cassandra
* incubator-pekko-persistence-dynamodb
* incubator-pekko-persistence-jdbc

**Comment by mdedetrich** [comment]
> > Okay we got something
> > ```
> > Both NEXUS_USER and NEXUS_PW environment variables for Apache Maven Nexus repo are empty strings
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Have to make an INFRA ticket
> 
> We've hit this a few times. Could you add a list of all this repo and a few others that we have made progress on - where we will soon also be publishing?
> 
> * incubator-pekko-connectors
> * incubator-pekko-connectors-kafka
> * incubator-pekko-grpc
> * incubator-pekko-management
> * incubator-pekko-persistence-cassandra
> * incubator-pekko-persistence-dynamodb
> * incubator-pekko-persistence-jdbc

Done

**Comment by mdedetrich** [comment]
@nvollmar So according to the INFRA ticket the credentials should be enabled for this repo but I am still getting issues but it may be due to some weird caching going on.

Can you just rebase this PR against master to a force a complete re-run just to confirm?

**Comment by nvollmar** [comment]
done

**Comment by mdedetrich** [comment]
Still failing with same problem, updated INFRA ticket.

**Comment by mdedetrich** [comment]
So from https://issues.apache.org/jira/browse/INFRA-24284?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=17696757#comment-17696757

> They are not missing, they are just not available to PRs that run from forks, for security reasons which should be obvious , credentials are not exposed.

So this explains it, @nvollmar Can you clean up this PR (i.e. re-enable it to to be only trigger after merge to `main` etc etc), we actually have to merge the PR into `main` for secrets to be available

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
