### PR TITLE
Publish artifacts

### PR DESCRIPTION
**Pull request by nvollmar**

### CODE REVIEW

**Review by mdedetrich — CHANGES_REQUESTED** [review]
So I am only blocking this for now because it won't work until sbt-apache-sonatype is integrated https://github.com/mdedetrich/sbt-apache-sonatype.

If you feel like it, you can do it in this PR or another PR or I can also do the work.

**Comment by mdedetrich** [comment]
I will just go ahead and integrate sbt-apache-sonatype, should be quite fast.

**Comment by nvollmar** [comment]
Thanks 👍

**Review by mdedetrich — APPROVED** [review]
Approving now since sbt-apache-sonatype has been integrated into project.

**Comment by mdedetrich** [comment]
Will merge it, even if it fails/doesn't work we then have something to work on later.

**Pull request merged**
